# Generated by Django 3.1.3 on 2020-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
